name = "worker"
main = "src/worker.js"
compatibility_date = "2024-11-29"
workers_dev = true
minify = true

[vars]
# Change this UUID before publishing (must be a valid V4 UUID)
UUID = "4e817682-b564-432d-9cee-c249606986d5"
WS_PATH = "/ws"
SUB_NAME = "sub"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
