name = "vless"
main = "src/worker.js"
compatibility_date = "2024-11-29"
workers_dev = true
minify = true

[vars]
# Change this UUID before publishing (must be a valid V4 UUID)
UUID = "11111111-1111-4111-8111-111111111111"
WS_PATH = "/ws"
SUB_NAME = "VLESS"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
